### ISSUE TITLE
Moving platform not in stl folder

### ISSUE THREAD

**Issue by julianstirling** [rwb27/openflexure_block_stage#11]
The last version where I can find the moving stage stl in the stl folder is:

```
commit a483b23867666ced6fbd4fc924379f1844d74ab3
Author: Richard Bowman <richard.bowman@cantab.net>
Date:   Mon Nov 5 09:33:21 2018 +0000

    Added a note about "betweenholes" versions
```

**Comment by morgatron** [comment]
Is the moving_stage STL from the previous version compatible with the rest of the parts from the latest? Or should I just print everything from the previous version?

**Comment by rwb27** [comment]
I've not changed anything that would make the old one incompatible, so I'd go ahead and use the previous revision of the moving platform with the latest revision of everything else.

**Comment by rwb27** [comment]
This issue should be fixed when we finally sort out CI for the STLs on the new repository on GitLab.  Our new home is: https://gitlab.com/openflexure/openflexure-block-stage/
