### ISSUE TITLE
"self tapping" M3 holes on the platforms strip easily

### ISSUE THREAD

**Issue by rwb27** [rwb27/openflexure_block_stage#5]
It would be good to update these with the ridged or triangulated holes that are used elsewhere in open flexure stuff...

**Comment by julianstirling** [comment]
The current pentagon has too small and inscribed area, can be tapped with a tap but excessive pressure is needed from the top. If hole is opened to 2.5mm with a drill it taps nicely.
The triangular holes for tapping are a good plan. It might be worth considering what the price is to have metal platforms which attach to the flexure stage with nut traps. This would let optics slide nicely and would significantly increase the lifetime of the platform.

**Comment by rwb27** [comment]
Julian's fixed this in the new repo https://gitlab.com/openflexure/openflexure-block-stage/
