### ISSUE TITLE
Screw holes incorrect sizes

### ISSUE THREAD

**Issue by julianstirling** [rwb27/openflexure_block_stage#9]
The holes on the moving platform which should be M3 clearance are hexagonal with a size of 3*1.15mm, the inscribed circle is 2.99mm. Even a close fit M3 clearance is specced as 3.2mm. This is causing a number of stages to self-tap both the platform and the xyz-table, leaving the platform raised or wobbly. This can be fixed with a drill or a knife but would be best to increase the size of $fn in openscad.

**Comment by rwb27** [comment]
I think you've fixed this in the new repository https://gitlab.com/openflexure/openflexure-block-stage/
